server:
  port: 8087
spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/paymentdb?authSource=admin
    redis:
      host: localhost
      port: 6379
  config:
    import: "optional:configserver:http://config-server:8888"

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  file:
    name: /app/logs/payment-service.log
  level:
    root: INFO
    org.springframework.cache: TRACE
  pattern:
    level: "%5p [${spring.application.name}, traceId=%X{traceId}, spanId=%X{spanId}]"

management:
  tracing:
    sampling:
      probability: 1.0  # capture all requests (dev only)
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

