server:
  port: 8086
spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/orderdb?authSource=admin
    redis:
      host: redis
      port: 6379
  cloud:
    config:
      enabled: false

  config:
    import-check:
      enabled: false

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  file:
    name: /app/logs/order-service.log
  level:
    root: INFO
    org.springframework.cache: TRACE
  pattern:
    level: "%5p [${spring.application.name}, traceId=%X{traceId}, spanId=%X{spanId}]"

management:
  tracing:
    sampling:
      probability: 1.0  # capture all requests (dev only)
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
  retry:
    instances:
      paymentService:
        maxAttempts: 3
        waitDuration: 2s

